# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='added_by',
            field=models.CharField(default='admin', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='modified_by',
            field=models.CharField(default='admin', max_length=30),
            preserve_default=False,
        ),
    ]
